### ISSUE TITLE
In some folders drex doesn't refresh properly leading to different errors

### ISSUE THREAD

**Issue by sergeypdev** [TheBlob42/drex.nvim#13] opened 2022-01-27 10:38 UTC
This is an example of such error:
![image](https://user-images.githubusercontent.com/78605863/151341698-c7ceb2d8-b4c2-48f6-8134-8f104fb97cd8.png)

It happens when I try to create a file. I can see that the file is created, but it doesn't show up in drex and as such it can't focus on it.

 I tried to debug it and come to the conclusion that it happens because drex window doesn't reload properly. Either because it doesn't detect file changes or because of something else.

It also doesn't refresh when I delete a file. The deleted file stays in the buffer.

This only happens in some directories, I'm not sure if it's because of their path or because of something inside them. 

**Platform**: OSX 12.1
**neovim version**: NVIM v0.7.0-dev

**Update**:
It seems to only be a problem for the root folder, subfolders keep working.

**Comment by TheBlob42** [comment] 2022-01-30 14:02
Ok I have prepared something to troubleshoot this a bit and hopefully find out what is going on:

- check out the `fs_debug` branch
- open nvim, open a DREX buffer, expand some directories, create a file in the root folder (where you face the problem)
- copy all print outputs

> you can use the following snippet to get all the debug outputs

```text
:redir @a
:messages
:redir END
:bnew
"ap
```

Post the output and all steps you have done here as a comment  
Hopefully this will give us a hint on what might cause your problem :slightly_smiling_face:

**Comment by TheBlob42** [comment] 2022-03-04 18:22
Hey :slightly_smiling_face: could you reproduce the issue since your last comment?
Otherwise I would close this ticket and rather open a new one should the issue re-appear in the future

**Comment by TheBlob42** [comment] 2022-03-16 19:49
I gonna close this issue for now.
If you encounter this issue again and/or have a way to reproduce it, please open a new ticket

**Closed by TheBlob42** 2022-03-16 19:49 UTC
